spring:
  mvc.view.suffix: .html
  mustache.servlet.cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seed?serverTimezone=Asia/Seoul
    #url: jdbc:mysql://database-1.c1np9azthax6.ap-northeast-2.rds.amazonaws.com/seed
    username: jin
    password: Deokjin7@
    #password: deokjin7845

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: rusttutorial@gmail.com
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
